export { default as react } from "./react.svg"
export { default as millLogo } from "./mill-logo.png"
export { default as cartSvg } from "./cart.svg"
export { default as deleteSvg } from "./delete.svg"
export { default as filtersSvg } from "./filters.svg"
export { default as homeSvg } from "./home.svg"
export { default as lupaSvg } from "./lupa.svg"
export { default as check } from "./check.svg"
export { default as checkB } from "./checkB.svg"
export { default as reload } from "./reload.svg"
export { default as pen } from "./pen.svg"
export { default as cargando } from "./cargando.svg"
export { default as entregado } from "./entregado.svg"
export { default as off } from "./switchOff.svg"
export { default as on } from "./switchOn.svg"
export { default as star } from "./star.svg"
export { default as tuerca } from "./tuerca.svg"
export { default as sesion } from "./sesion.svg"
export { default as sesionB } from "./sesionB.svg"
export { default as dahs } from "./dash.svg"
export { default as  lista} from "./lista.svg"
export { default as  plato} from "./plato.svg"
export { default as  user} from "./user.svg"
export { default as  stats} from "./stats.svg"
export { default as  git} from "./github.svg"
export { default as  linkedin} from "./linkedin.svg"
export { default as  about} from "./people-group-solid.svg"

export { default as juanjo } from "./juanjo.png"
export { default as  ire} from "./Ire.jpeg"
export { default as  gina} from "./gina.png"
export { default as  gian} from "./gian.png"
export { default as  nico} from "./nico.jpeg"
export { default as  fede} from "./FEDE.png"
export { default as  carlos} from "./carlos.jpeg"
export { default as  tobias} from "./tobias.png"
export const bg = "https://www.themillrestaurants.com/wp-content/themes/themills/img/home-bg.jpg"

