// export * from "./About"
export * from "./Home"
export * from "./Chart"
export * from "./NotFound"
export * from "./Menu"
export * from "./Login"
export * from "./Dashboard"
export * from "./Cart"
export * from "./MenuDetail"
export * from "./WithoutPermissions"
export * from "./PanelAdmin"
export * from "./Rating"
export * from "./About"
// export * from "./LoginPage"
// export * from "./Orders"
